version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - echo Installing NGNIX
      - sudo apt-get update
      - sudo apt-get install nginx -y
      - npm install
  pre_build:
    commands:
      - echo Running tests...
  build:
    commands:
      - echo Building the project...
      - npm run build
  post_build:
    commands:
      - echo configuring NGNIX
artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*'
    - '!**/*.log'
